# Generated by Django 5.2.1 on 2025-05-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('directions', models.JSONField(default=list)),
                ('titles', models.JSONField(default=list)),
                ('experience', models.IntegerField()),
                ('is_reliable', models.BooleanField(default=False)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('serts', models.JSONField(default=list)),
            ],
        ),
    ]
