# Generated by Django 5.2.1 on 2025-05-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='experience',
        ),
    ]
