# Generated by Django 5.2.1 on 2025-06-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0002_remove_specialist_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='experience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
