# Generated by Django 5.2.1 on 2025-06-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0003_specialist_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='education',
        ),
    ]
