# Generated by Django 5.2.1 on 2025-06-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0004_remove_specialist_education'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialist',
            options={'ordering': ['name'], 'verbose_name': 'Специалист', 'verbose_name_plural': 'Специалисты'},
        ),
        migrations.AlterField(
            model_name='specialist',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='degree',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Степень/звание'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='directions',
            field=models.JSONField(default=list, verbose_name='Направления деятельности'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='experience',
            field=models.IntegerField(blank=True, null=True, verbose_name='Опыт работы (лет)'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='image',
            field=models.CharField(max_length=255, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='is_reliable',
            field=models.BooleanField(default=False, verbose_name='Проверенный специалист'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя специалиста'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='serts',
            field=models.JSONField(default=list, verbose_name='Сертификаты'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='titles',
            field=models.JSONField(default=list, verbose_name='Должности'),
        ),
    ]
