# Generated by Django 5.2.1 on 2025-05-27 14:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialists', '0002_remove_specialist_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('is_service', models.BooleanField(default=False, verbose_name='Медицинская услуга')),
                ('is_goods', models.BooleanField(default=False, verbose_name='Товары')),
                ('is_analysis', models.BooleanField(default=False, verbose_name='Анализы')),
                ('service_name', models.CharField(blank=True, max_length=255, verbose_name='Название услуги')),
                ('service_direction', models.CharField(blank=True, max_length=255, verbose_name='Направление услуги')),
                ('service_type', models.CharField(blank=True, max_length=255, verbose_name='Тип услуги')),
                ('additional_info', models.JSONField(blank=True, default=dict, verbose_name='Дополнительная информация')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_new', models.BooleanField(default=True, verbose_name='Новая заявка')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specialists.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
