# Generated by Django 5.2.1 on 2025-05-14 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('main_image', models.CharField(max_length=255)),
                ('procedure_number', models.IntegerField()),
                ('procedure_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('rehab_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('service_direction', models.IntegerField(blank=True, null=True)),
                ('service_type', models.IntegerField(blank=True, null=True)),
                ('specialists', models.JSONField(default=list)),
                ('readings', models.TextField(blank=True, null=True)),
                ('contraindications', models.TextField(blank=True, null=True)),
                ('devices', models.TextField(blank=True, null=True)),
                ('need_to_have', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(default=list)),
                ('serts', models.JSONField(default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
