# Generated by Django 5.2.1 on 2025-05-14 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('directions', models.JSONField(default=list)),
                ('titles', models.JSONField(default=list)),
                ('experience', models.IntegerField()),
                ('is_reliable', models.BooleanField(default=False)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('serts', models.JSONField(default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='specialists',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.specialist'),
        ),
    ]
