# Generated by Django 5.2.1 on 2025-05-23 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_specialist_alter_service_specialists'),
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='specialists',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='specialists.specialist'),
        ),
        migrations.DeleteModel(
            name='Specialist',
        ),
    ]
