# Generated by Django 5.2.1 on 2025-05-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_specialists_delete_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='specialists',
            field=models.JSONField(default=list),
        ),
    ]
