# Generated by Django 5.2.1 on 2025-06-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='specialists',
            new_name='job_titles',
        ),
    ]
