# Generated by Django 5.2.1 on 2025-05-27 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Изображение товара')),
                ('service_direction', models.PositiveIntegerField(verbose_name='ID направления услуги')),
                ('article', models.CharField(max_length=100, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sizes', models.CharField(blank=True, max_length=255, verbose_name='Размеры')),
                ('product_care', models.TextField(blank=True, verbose_name='Уход за товаром')),
                ('important', models.TextField(blank=True, verbose_name='Важная информация')),
                ('contraindications', models.TextField(blank=True, verbose_name='Противопоказания')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('enabled', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_direction'], name='goods_good_service_a3b0af_idx'), models.Index(fields=['enabled'], name='goods_good_enabled_d10604_idx'), models.Index(fields=['slug'], name='goods_good_slug_2db51c_idx'), models.Index(fields=['article'], name='goods_good_article_d4302e_idx')],
            },
        ),
    ]
