# Generated by Django 5.2.1 on 2025-06-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_good_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='sizes',
            field=models.CharField(blank=True, verbose_name='Размеры'),
        ),
    ]
