# Generated by Django 5.2.1 on 2025-06-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_good_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='article',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикул'),
        ),
    ]
