# Generated by Django 5.2.1 on 2025-06-27 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок статьи')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Изображение')),
                ('time_to_read', models.PositiveIntegerField(blank=True, help_text='Время чтения статьи в минутах', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время чтения (в минутах)')),
                ('service_direction', models.PositiveIntegerField(blank=True, help_text='Связь с направлением услуги', null=True, verbose_name='ID направления услуги')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('enabled', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_direction'], name='news_news_service_dcb58d_idx'), models.Index(fields=['enabled'], name='news_news_enabled_115d52_idx'), models.Index(fields=['slug'], name='news_news_slug_915ecd_idx'), models.Index(fields=['created_at'], name='news_news_created_b5b178_idx')],
            },
        ),
    ]
