# Generated by Django 5.2.1 on 2025-05-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_directions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedirection',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
