# Generated by Django 5.2.1 on 2025-05-27 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название анализа')),
                ('service_direction', models.PositiveIntegerField(verbose_name='ID направления услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость анализа')),
                ('nomenclature', models.CharField(blank=True, max_length=255, verbose_name='Номенклатура')),
                ('method', models.CharField(blank=True, max_length=255, verbose_name='Метод определения')),
                ('time', models.CharField(blank=True, max_length=100, verbose_name='Срок исполнения')),
                ('characteristic', models.TextField(blank=True, verbose_name='Характеристика')),
                ('rules', models.TextField(blank=True, verbose_name='Правила подготовки')),
                ('readings', models.TextField(blank=True, verbose_name='Показания')),
                ('contraindications', models.TextField(blank=True, verbose_name='Противопоказания')),
                ('depends_to', models.CharField(blank=True, max_length=255, verbose_name='Зависит от')),
                ('enabled', models.BooleanField(default=True, verbose_name='Активен')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Анализ',
                'verbose_name_plural': 'Анализы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_direction'], name='tests_test_service_765547_idx'), models.Index(fields=['enabled'], name='tests_test_enabled_005eb7_idx'), models.Index(fields=['slug'], name='tests_test_slug_68c95b_idx')],
            },
        ),
    ]
