# Generated by Django 5.2.1 on 2025-06-06 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='depends_to',
            field=models.CharField(blank=True, verbose_name='Зависит от'),
        ),
        migrations.AlterField(
            model_name='test',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость анализа'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time',
            field=models.CharField(blank=True, max_length=255, verbose_name='Срок исполнения'),
        ),
    ]
