# Generated by Django 5.2.1 on 2025-06-06 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_test_depends_to_alter_test_price_and_more'),
        ('tests', '0002_alter_test_price'),
    ]

    operations = [
    ]
